name: CarSecurity
description:  
version: 2.0.1
author: Samuel Toribio
homepage: https://github.com/samtts14/CarSecure.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_radial_menu:
  image_picker: ^0.8.4+4
  path_provider: ^2.0.2


flutter:
    uses-material-design: true
